# Generated by Django 5.0.3 on 2024-05-05 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='件名')),
                ('text', models.TextField(verbose_name='内容')),
                ('viewed', models.BooleanField(default=False, verbose_name='閲覧')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to=settings.AUTH_USER_MODEL, verbose_name='受信者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to=settings.AUTH_USER_MODEL, verbose_name='送信者')),
            ],
        ),
    ]
