# Generated by Django 5.0.3 on 2024-04-01 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='タイトル')),
                ('text', models.TextField(blank=True, verbose_name='投稿文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('file', models.FileField(upload_to='', verbose_name='添付ファイル')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
        ),
    ]
