# Generated by Django 5.0.3 on 2024-04-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='添付ファイル'),
        ),
    ]
